import { colors } from "@/lib/theme/colors";
import { useState } from "react";
import {
  View,
  Text,
  TextInput,
  Pressable,
  ActivityIndicator,
  KeyboardAvoidingView,
  Platform,
  ScrollView,
  Share,
  Image,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { LinearGradient } from "expo-linear-gradient";
import * as Clipboard from "expo-clipboard";
import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { supabase } from "@/lib/supabase";
import { useSession } from "@/lib/auth-context";
import { StepProgressBar } from "@/components/ui";
import { ONBOARDING_CREAM, ONBOARDING_IMAGES } from "@/lib/onboarding-images";

export default function CreateHouseholdScreen() {
  const router = useRouter();
  const { user } = useSession();
  const [householdName, setHouseholdName] = useState("");
  const [inviteCode, setInviteCode] = useState<string | null>(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const [focused, setFocused] = useState(false);

  const trimmedName = householdName.trim();

  async function handleCreate() {
    if (!trimmedName) {
      setError("Please enter a household name");
      return;
    }

    setError("");
    setLoading(true);
    try {
      // 1. Insert household (invite_code is auto-generated by DB trigger)
      const { data: household, error: householdError } = await supabase
        .from("households")
        .insert({
          name: trimmedName,
          created_by: user!.id,
        })
        .select()
        .single();

      if (householdError) {
        setError(householdError.message);
        return;
      }

      // 2. Add creator as first member
      const { error: memberError } = await supabase
        .from("household_members")
        .insert({
          household_id: household.id,
          user_id: user!.id,
          role: "creator",
        });

      if (memberError) {
        setError(memberError.message);
        return;
      }

      // household_settings is auto-created by the on_household_created trigger

      // Show invite code
      setInviteCode(household.invite_code);
    } catch {
      setError("Something went wrong. Please try again.");
    } finally {
      setLoading(false);
    }
  }

  const [copied, setCopied] = useState(false);

  async function handleShare() {
    if (!inviteCode) return;
    try {
      await Share.share({
        message: `Join my household on RoomY! Use invite code: ${inviteCode}`,
      });
    } catch {
      // User cancelled share or share failed -- no action needed
    }
  }

  async function handleCopyCode() {
    if (!inviteCode) return;
    await Clipboard.setStringAsync(inviteCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function handleContinue() {
    router.push("/(onboarding)/module-quiz");
  }

  // ===== Invite code celebration after creation =====
  if (inviteCode) {
    const formattedCode =
      inviteCode.slice(0, 4) + " " + inviteCode.slice(4);

    return (
      <SafeAreaView style={{ flex: 1, backgroundColor: ONBOARDING_CREAM }}>
        {/* No StepProgressBar -- celebration moment */}
        <ScrollView
          contentContainerStyle={{
            flexGrow: 1,
            paddingHorizontal: 32,
            paddingBottom: 32,
          }}
          showsVerticalScrollIndicator={false}
        >
          {/* Illustration hero */}
          <View style={{ alignItems: "center", marginTop: 16 }}>
            <Image
              source={ONBOARDING_IMAGES.inviteCode}
              style={{ width: "100%", height: 240 }}
              resizeMode="contain"
            />
          </View>

          {/* Title + subtitle */}
          <View style={{ alignItems: "center", marginTop: 20, marginBottom: 24 }}>
            <Text
              style={{
                fontSize: 28,
                fontWeight: "700",
                color: colors.neutral.text,
                textAlign: "center",
              }}
            >
              You're All Set!
            </Text>
            <Text
              style={{
                fontSize: 15,
                color: colors.neutral.secondary,
                textAlign: "center",
                marginTop: 6,
              }}
            >
              Share this code with your roommates
            </Text>
          </View>

          {/* Dark gradient invite code card */}
          <LinearGradient
            colors={[colors.brand.DEFAULT, colors.brand.dark]}
            start={{ x: 0, y: 0 }}
            end={{ x: 1, y: 1 }}
            style={{
              borderRadius: 16,
              padding: 24,
              alignItems: "center",
              marginBottom: 24,
            }}
          >
            <Text
              style={{
                fontSize: 11,
                fontWeight: "600",
                letterSpacing: 1.1,
                color: "#94A3B8",
                textTransform: "uppercase",
                marginBottom: 8,
              }}
            >
              INVITE CODE
            </Text>
            <Text
              style={{
                fontSize: 36,
                fontWeight: "700",
                letterSpacing: 4,
                color: "#FFFFFF",
                fontVariant: ["tabular-nums"],
              }}
            >
              {formattedCode}
            </Text>
          </LinearGradient>

          {/* Share with Roommates button */}
          <Pressable
            style={{
              backgroundColor: colors.brand.DEFAULT,
              borderRadius: 16,
              paddingVertical: 16,
              flexDirection: "row",
              alignItems: "center",
              justifyContent: "center",
              marginBottom: 12,
            }}
            onPress={handleShare}
          >
            <Ionicons
              name="share-outline"
              size={22}
              color="#fff"
              style={{ marginRight: 8 }}
            />
            <Text
              style={{
                fontSize: 17,
                fontWeight: "700",
                color: "#FFFFFF",
              }}
            >
              Share with Roommates
            </Text>
          </Pressable>

          {/* Copy code text link */}
          <Pressable
            style={{
              alignItems: "center",
              paddingVertical: 8,
              marginBottom: 16,
            }}
            onPress={handleCopyCode}
          >
            <Text
              style={{
                fontSize: 15,
                fontWeight: "600",
                color: colors.brand.DEFAULT,
              }}
            >
              {copied ? "Copied!" : "Copy code"}
            </Text>
          </Pressable>

          {/* Continue Setup button */}
          <Pressable
            style={{
              borderWidth: 2,
              borderColor: colors.brand.DEFAULT,
              borderRadius: 16,
              paddingVertical: 16,
              alignItems: "center",
            }}
            onPress={handleContinue}
          >
            <Text
              style={{
                fontSize: 17,
                fontWeight: "700",
                color: colors.brand.dark,
              }}
            >
              Continue Setup
            </Text>
          </Pressable>
        </ScrollView>
      </SafeAreaView>
    );
  }

  // ===== Name form step (RESTYLED) =====
  return (
    <SafeAreaView style={{ flex: 1, backgroundColor: ONBOARDING_CREAM }}>
      <StepProgressBar
        currentStep={1}
        totalSteps={3}
        onBack={() => router.back()}
      />

      <KeyboardAvoidingView
        style={{ flex: 1 }}
        behavior={Platform.OS === "ios" ? "padding" : "height"}
      >
        <ScrollView
          contentContainerStyle={{
            flexGrow: 1,
            paddingHorizontal: 32,
            paddingBottom: 32,
          }}
          keyboardShouldPersistTaps="handled"
          showsVerticalScrollIndicator={false}
        >
          {/* Illustration hero */}
          <View style={{ alignItems: "center", marginTop: 8 }}>
            <Image
              source={ONBOARDING_IMAGES.nameHousehold}
              style={{ width: "100%", height: 220 }}
              resizeMode="contain"
            />
          </View>

          {/* Title + subtitle */}
          <View style={{ alignItems: "center", marginBottom: 24 }}>
            <Text
              style={{
                fontSize: 26,
                fontWeight: "700",
                color: colors.neutral.text,
                textAlign: "center",
              }}
            >
              Name Your Household
            </Text>
            <Text
              style={{
                fontSize: 15,
                color: colors.neutral.secondary,
                textAlign: "center",
                marginTop: 6,
              }}
            >
              Give your home a name your roommates will recognize
            </Text>
          </View>

          {/* Error */}
          {error ? (
            <View className="mb-4 rounded-xl bg-red-50 px-4 py-3">
              <Text className="text-sm text-red-600">{error}</Text>
            </View>
          ) : null}

          {/* Household name input */}
          <View style={{ marginBottom: 24 }}>
            <TextInput
              className={`rounded-2xl px-4 py-3.5 text-base text-neutral-text ${
                error
                  ? "border-2 border-semantic-error bg-white"
                  : focused
                    ? "border-2 border-brand bg-white"
                    : "bg-[#F5F5F5]"
              }`}
              placeholder="e.g., The Lake House"
              placeholderTextColor={colors.neutral.tertiary}
              value={householdName}
              onChangeText={(text) => {
                setHouseholdName(text);
                if (error) setError("");
              }}
              onFocus={() => setFocused(true)}
              onBlur={() => setFocused(false)}
              autoCapitalize="words"
              editable={!loading}
              autoFocus
            />
          </View>

          {/* Create button */}
          <Pressable
            className={`items-center rounded-2xl py-4 ${
              !trimmedName || loading
                ? "bg-brand/50"
                : "bg-brand active:bg-brand-dark"
            }`}
            onPress={handleCreate}
            disabled={!trimmedName || loading}
          >
            {loading ? (
              <ActivityIndicator color="#fff" />
            ) : (
              <Text className="text-lg font-bold text-white">
                Create Household
              </Text>
            )}
          </Pressable>
        </ScrollView>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}
