import { useState } from "react";
import {
  View,
  Text,
  TextInput,
  Pressable,
  ActivityIndicator,
  KeyboardAvoidingView,
  Platform,
  ScrollView,
  Share,
} from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { supabase } from "@/lib/supabase";
import { useSession } from "@/lib/auth-context";

export default function CreateHouseholdScreen() {
  const router = useRouter();
  const { user } = useSession();
  const [householdName, setHouseholdName] = useState("");
  const [inviteCode, setInviteCode] = useState<string | null>(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  const trimmedName = householdName.trim();

  async function handleCreate() {
    if (!trimmedName) {
      setError("Please enter a household name");
      return;
    }

    setError("");
    setLoading(true);
    try {
      // 1. Insert household (invite_code is auto-generated by DB trigger)
      const { data: household, error: householdError } = await supabase
        .from("households")
        .insert({
          name: trimmedName,
          created_by: user!.id,
        })
        .select()
        .single();

      if (householdError) {
        setError(householdError.message);
        return;
      }

      // 2. Add creator as first member
      const { error: memberError } = await supabase
        .from("household_members")
        .insert({
          household_id: household.id,
          user_id: user!.id,
          role: "creator",
        });

      if (memberError) {
        setError(memberError.message);
        return;
      }

      // household_settings is auto-created by the on_household_created trigger

      // Show invite code
      setInviteCode(household.invite_code);
    } catch {
      setError("Something went wrong. Please try again.");
    } finally {
      setLoading(false);
    }
  }

  async function handleShare() {
    if (!inviteCode) return;
    try {
      await Share.share({
        message: `Join my household on RoomY! Use code: ${inviteCode}`,
      });
    } catch {
      // User cancelled share or share failed -- no action needed
    }
  }

  function handleContinue() {
    router.push("/(onboarding)/module-quiz");
  }

  // Invite code display after creation
  if (inviteCode) {
    // Format code with spaces for readability (e.g., "ABCD EFGH")
    const formattedCode =
      inviteCode.slice(0, 4) + " " + inviteCode.slice(4);

    return (
      <View className="flex-1 bg-surface-50 px-8 pt-20">
        <ScrollView
          contentContainerClassName="flex-grow justify-center pb-12"
          showsVerticalScrollIndicator={false}
        >
          {/* Success icon */}
          <View className="mb-6 items-center">
            <View className="mb-6 h-24 w-24 items-center justify-center rounded-full bg-accent-500/20">
              <Ionicons name="checkmark-circle" size={56} color="#66bb6a" />
            </View>
            <Text className="text-3xl font-bold text-gray-800">
              {trimmedName} is ready!
            </Text>
            <Text className="mt-2 text-center text-base text-gray-500">
              Share this code with your roommates so they can join
            </Text>
          </View>

          {/* Invite code display */}
          <View className="mb-6 items-center rounded-2xl bg-white p-8 shadow-sm">
            <Text className="mb-2 text-sm font-medium text-gray-400">
              INVITE CODE
            </Text>
            <Text
              className="text-4xl font-bold tracking-widest text-primary-600"
              style={{ fontVariant: ["tabular-nums"] }}
            >
              {formattedCode}
            </Text>
            <Text className="mt-3 text-xs text-gray-400">
              Code expires in 7 days. You can regenerate it in Settings.
            </Text>
          </View>

          {/* Share button */}
          <Pressable
            className="mb-4 flex-row items-center justify-center rounded-2xl bg-primary-500 py-4 active:bg-primary-600"
            onPress={handleShare}
          >
            <Ionicons
              name="share-outline"
              size={22}
              color="#fff"
              style={{ marginRight: 8 }}
            />
            <Text className="text-lg font-bold text-white">
              Share with Roommates
            </Text>
          </Pressable>

          {/* Continue button */}
          <Pressable
            className="items-center rounded-2xl border-2 border-primary-500 py-4 active:bg-primary-50"
            onPress={handleContinue}
          >
            <Text className="text-lg font-bold text-primary-600">
              Continue Setup
            </Text>
          </Pressable>
        </ScrollView>
      </View>
    );
  }

  // Household name form
  return (
    <KeyboardAvoidingView
      className="flex-1 bg-surface-50"
      behavior={Platform.OS === "ios" ? "padding" : "height"}
    >
      <ScrollView
        contentContainerClassName="flex-grow justify-center px-8 py-12"
        keyboardShouldPersistTaps="handled"
      >
        {/* Header */}
        <View className="mb-8 items-center">
          <View className="mb-6 h-24 w-24 items-center justify-center rounded-full bg-primary-100">
            <Ionicons name="home" size={44} color="#f9a825" />
          </View>
          <Text className="text-3xl font-bold text-gray-800">
            Name Your Household
          </Text>
          <Text className="mt-2 text-center text-base text-gray-500">
            Pick something your roommates will recognize
          </Text>
        </View>

        {/* Error */}
        {error ? (
          <View className="mb-4 rounded-xl bg-red-50 px-4 py-3">
            <Text className="text-sm text-red-600">{error}</Text>
          </View>
        ) : null}

        {/* Household name input */}
        <View className="mb-8">
          <Text className="mb-1.5 text-sm font-medium text-gray-700">
            Household Name
          </Text>
          <TextInput
            className={`rounded-xl border bg-white px-4 py-3.5 text-base text-gray-800 ${
              error ? "border-red-400" : "border-surface-200"
            }`}
            placeholder='e.g., "The Elm Street Crew"'
            placeholderTextColor="#9ca3af"
            value={householdName}
            onChangeText={(text) => {
              setHouseholdName(text);
              if (error) setError("");
            }}
            autoCapitalize="words"
            editable={!loading}
            autoFocus
          />
        </View>

        {/* Create button */}
        <Pressable
          className={`items-center rounded-2xl py-4 ${
            !trimmedName || loading
              ? "bg-primary-300"
              : "bg-primary-500 active:bg-primary-600"
          }`}
          onPress={handleCreate}
          disabled={!trimmedName || loading}
        >
          {loading ? (
            <ActivityIndicator color="#fff" />
          ) : (
            <Text className="text-lg font-bold text-white">
              Create Household
            </Text>
          )}
        </Pressable>
      </ScrollView>
    </KeyboardAvoidingView>
  );
}
