import { colors } from "@/lib/theme/colors";
import { useState } from "react";
import {
  View,
  Text,
  TextInput,
  Pressable,
  ActivityIndicator,
  KeyboardAvoidingView,
  Platform,
  ScrollView,
  Share,
  Image,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { supabase } from "@/lib/supabase";
import { useSession } from "@/lib/auth-context";
import { IconContainer, StepProgressBar } from "@/components/ui";
import { ONBOARDING_CREAM, ONBOARDING_IMAGES } from "@/lib/onboarding-images";

export default function CreateHouseholdScreen() {
  const router = useRouter();
  const { user } = useSession();
  const [householdName, setHouseholdName] = useState("");
  const [inviteCode, setInviteCode] = useState<string | null>(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const [focused, setFocused] = useState(false);

  const trimmedName = householdName.trim();

  async function handleCreate() {
    if (!trimmedName) {
      setError("Please enter a household name");
      return;
    }

    setError("");
    setLoading(true);
    try {
      // 1. Insert household (invite_code is auto-generated by DB trigger)
      const { data: household, error: householdError } = await supabase
        .from("households")
        .insert({
          name: trimmedName,
          created_by: user!.id,
        })
        .select()
        .single();

      if (householdError) {
        setError(householdError.message);
        return;
      }

      // 2. Add creator as first member
      const { error: memberError } = await supabase
        .from("household_members")
        .insert({
          household_id: household.id,
          user_id: user!.id,
          role: "creator",
        });

      if (memberError) {
        setError(memberError.message);
        return;
      }

      // household_settings is auto-created by the on_household_created trigger

      // Show invite code
      setInviteCode(household.invite_code);
    } catch {
      setError("Something went wrong. Please try again.");
    } finally {
      setLoading(false);
    }
  }

  async function handleShare() {
    if (!inviteCode) return;
    try {
      await Share.share({
        message: `Join my household on RoomY! Use code: ${inviteCode}`,
      });
    } catch {
      // User cancelled share or share failed -- no action needed
    }
  }

  function handleContinue() {
    router.push("/(onboarding)/module-quiz");
  }

  // ===== Invite code display after creation (UNCHANGED -- Plan 04 will restyle) =====
  if (inviteCode) {
    // Format code with spaces for readability (e.g., "ABCD EFGH")
    const formattedCode =
      inviteCode.slice(0, 4) + " " + inviteCode.slice(4);

    return (
      <View className="flex-1 bg-neutral-bg px-8 pt-20">
        <ScrollView
          contentContainerClassName="flex-grow justify-center pb-12"
          showsVerticalScrollIndicator={false}
        >
          {/* Success icon */}
          <View className="mb-6 items-center">
            <View className="mb-6 h-24 w-24 items-center justify-center rounded-full bg-semantic-success/20">
              <Ionicons name="checkmark-circle" size={56} color={colors.semantic.success} />
            </View>
            <Text className="text-3xl font-bold text-gray-800">
              {trimmedName} is ready!
            </Text>
            <Text className="mt-2 text-center text-base text-gray-500">
              Share this code with your roommates so they can join
            </Text>
          </View>

          {/* Invite code display */}
          <View className="mb-6 items-center rounded-2xl bg-white p-8 shadow-sm">
            <Text className="mb-2 text-sm font-medium text-gray-400">
              INVITE CODE
            </Text>
            <Text
              className="text-4xl font-bold tracking-widest text-brand-dark"
              style={{ fontVariant: ["tabular-nums"] }}
            >
              {formattedCode}
            </Text>
            <Text className="mt-3 text-xs text-gray-400">
              Code expires in 7 days. You can regenerate it in Settings.
            </Text>
          </View>

          {/* Share button */}
          <Pressable
            className="mb-4 flex-row items-center justify-center rounded-2xl bg-brand py-4 active:bg-brand-dark"
            onPress={handleShare}
          >
            <Ionicons
              name="share-outline"
              size={22}
              color="#fff"
              style={{ marginRight: 8 }}
            />
            <Text className="text-lg font-bold text-white">
              Share with Roommates
            </Text>
          </Pressable>

          {/* Continue button */}
          <Pressable
            className="items-center rounded-2xl border-2 border-brand py-4 active:bg-brand-light"
            onPress={handleContinue}
          >
            <Text className="text-lg font-bold text-brand-dark">
              Continue Setup
            </Text>
          </Pressable>
        </ScrollView>
      </View>
    );
  }

  // ===== Name form step (RESTYLED) =====
  return (
    <SafeAreaView style={{ flex: 1, backgroundColor: ONBOARDING_CREAM }}>
      <StepProgressBar
        currentStep={1}
        totalSteps={3}
        onBack={() => router.back()}
      />

      <KeyboardAvoidingView
        style={{ flex: 1 }}
        behavior={Platform.OS === "ios" ? "padding" : "height"}
      >
        <ScrollView
          contentContainerStyle={{
            flexGrow: 1,
            paddingHorizontal: 32,
            paddingBottom: 32,
          }}
          keyboardShouldPersistTaps="handled"
          showsVerticalScrollIndicator={false}
        >
          {/* Illustration hero */}
          <View style={{ alignItems: "center", marginTop: 8 }}>
            <Image
              source={ONBOARDING_IMAGES.nameHousehold}
              style={{ width: "100%", height: 220 }}
              resizeMode="contain"
            />
          </View>

          {/* Branded house icon */}
          <View style={{ alignItems: "center", marginTop: 16, marginBottom: 12 }}>
            <IconContainer name="home" variant="brand" size={24} />
          </View>

          {/* Title + subtitle */}
          <View style={{ alignItems: "center", marginBottom: 24 }}>
            <Text
              style={{
                fontSize: 26,
                fontWeight: "700",
                color: colors.neutral.text,
                textAlign: "center",
              }}
            >
              Name Your Household
            </Text>
            <Text
              style={{
                fontSize: 15,
                color: colors.neutral.secondary,
                textAlign: "center",
                marginTop: 6,
              }}
            >
              Give your home a name your roommates will recognize
            </Text>
          </View>

          {/* Error */}
          {error ? (
            <View className="mb-4 rounded-xl bg-red-50 px-4 py-3">
              <Text className="text-sm text-red-600">{error}</Text>
            </View>
          ) : null}

          {/* Household name input */}
          <View style={{ marginBottom: 24 }}>
            <TextInput
              className={`rounded-2xl px-4 py-3.5 text-base text-neutral-text ${
                error
                  ? "border-2 border-semantic-error bg-white"
                  : focused
                    ? "border-2 border-brand bg-white"
                    : "bg-[#F5F5F5]"
              }`}
              placeholder="e.g., The Lake House"
              placeholderTextColor={colors.neutral.tertiary}
              value={householdName}
              onChangeText={(text) => {
                setHouseholdName(text);
                if (error) setError("");
              }}
              onFocus={() => setFocused(true)}
              onBlur={() => setFocused(false)}
              autoCapitalize="words"
              editable={!loading}
              autoFocus
            />
          </View>

          {/* Create button */}
          <Pressable
            className={`items-center rounded-2xl py-4 ${
              !trimmedName || loading
                ? "bg-brand/50"
                : "bg-brand active:bg-brand-dark"
            }`}
            onPress={handleCreate}
            disabled={!trimmedName || loading}
          >
            {loading ? (
              <ActivityIndicator color="#fff" />
            ) : (
              <Text className="text-lg font-bold text-white">
                Create Household
              </Text>
            )}
          </Pressable>
        </ScrollView>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}
